### ISSUE TITLE
Advanced Map no longer working on macOS 14.4 (23E214)

### ISSUE THREAD

**Issue by 5T33Z0** [notjosh/AdvancedMap#8]
It seems that Apple changed more things under the hood. The 3D globe is no longer working on my Lenovo T490 after updating to macOS 14.4.

![Bildschirmfoto 2024-03-08 um 12 39 51](https://github.com/notjosh/AdvancedMap/assets/76865553/40d7f476-ad7c-4f55-ad92-d1a5247e2f2e)

 **iGPU**: Intel UHD 620, spoofed as Intel UHD 630

**Comment by narcyzzo** [comment]
same, RX 6700 XT

**Comment by notjosh** [comment]
Nuts. My hackintosh is still on 14.3, so I'll get it upgraded and try to work out what's changed. Fingers crossed it's something minor.

**Comment by notjosh** [comment]
I won't be on my Intel machine until tomorrow (hopefully!), but I wrote a quick script that dumps values (+ some debug info) so we might be able to find a suitable replacement value.

If either of you have Xcode installed and want to compile a script, it's at https://gist.github.com/notjosh/01ea1f424c35ce6c423477b7b780a0f1. Would be interested if values have changed on 14.4.

For me on my M1, the output looks like:

```sh
$ cc dumper.m -o dumper -framework Foundation -framework Metal -lMobileGestalt -O3
$ ./dumper
2024-03-15 21:11:58.642 dumper[6607:179434] macOS version: Version 14.4 (Build 23E214)
2024-03-15 21:11:58.642 dumper[6607:179434] Architecture: arm64
2024-03-15 21:11:58.642 dumper[6607:179434] GPUs (
        {
        MTLGPUFamilyApple1 = 1;
        MTLGPUFamilyApple2 = 1;
        MTLGPUFamilyApple3 = 1;
        MTLGPUFamilyApple4 = 1;
        MTLGPUFamilyApple5 = 1;
        MTLGPUFamilyApple6 = 1;
        MTLGPUFamilyApple7 = 1;
        MTLGPUFamilyApple8 = 0;
        MTLGPUFamilyApple9 = 0;
        MTLGPUFamilyCommon1 = 1;
        MTLGPUFamilyCommon2 = 1;
        MTLGPUFamilyCommon3 = 1;
        MTLGPUFamilyMac2 = 1;
        MTLGPUFamilyMetal3 = 1;
        name = "Apple M1 Pro";
    }
)
2024-03-15 21:11:58.642 dumper[6607:179434] {
    DeviceSupportsActiveNFCReadingOnly = 0;
    DeviceSupportsAdvancedMapRendering = 1;
    DeviceSupportsCorrectedTemperature = 0;
    DeviceSupportsEnhancedMultitasking = 0;
    DeviceSupportsHeartRateVariability = 1;
    DeviceSupportsSideButtonClickSpeed = 0;
    DeviceSupportsSingleCameraPortrait = 0;
    DeviceSupportsStereoAudioRecording = 0;
    FrontCameraOffsetFromDisplayCenter = "<null>";
    FrontFacingCameraAutoHDRCapability = 1;
    RearFacingCameraMaxVideoZoomFactor = 3;
    RearFacingCameraModuleSerialNumber = "<null>";
    RearFacingLowLightCameraCapability = 0;
    RenderWideGamutImagesAtDisplayTime = 1;
}
```

**Comment by narcyzzo** [comment]
2024-03-15 21:35:33.077 dumper[1024:9851] macOS version: Version 14.4 (Build 23E214)
2024-03-15 21:35:33.077 dumper[1024:9851] Architecture: x86_64
2024-03-15 21:35:33.077 dumper[1024:9851] GPUs (
        {
        MTLGPUFamilyApple1 = 0;
        MTLGPUFamilyApple2 = 0;
        MTLGPUFamilyApple3 = 0;
        MTLGPUFamilyApple4 = 0;
        MTLGPUFamilyApple5 = 0;
        MTLGPUFamilyApple6 = 0;
        MTLGPUFamilyApple7 = 0;
        MTLGPUFamilyApple8 = 0;
        MTLGPUFamilyApple9 = 0;
        MTLGPUFamilyCommon1 = 1;
        MTLGPUFamilyCommon2 = 1;
        MTLGPUFamilyCommon3 = 1;
        MTLGPUFamilyMac2 = 1;
        MTLGPUFamilyMetal3 = 1;
        name = "AMD Radeon HD GFX10 Family Unknown Prototype";
    }
)
2024-03-15 21:35:33.077 dumper[1024:9851] {
    DeviceSupportsActiveNFCReadingOnly = 0;
    DeviceSupportsAdvancedMapRendering = 0;
    DeviceSupportsCorrectedTemperature = 0;
    DeviceSupportsEnhancedMultitasking = 0;
    DeviceSupportsHeartRateVariability = 1;
    DeviceSupportsSideButtonClickSpeed = 0;
    DeviceSupportsSingleCameraPortrait = 0;
    DeviceSupportsStereoAudioRecording = 0;
    FrontCameraOffsetFromDisplayCenter = "<null>";
    FrontFacingCameraAutoHDRCapability = 0;
    RearFacingCameraMaxVideoZoomFactor = "<null>";
    RearFacingCameraModuleSerialNumber = "<null>";
    RearFacingLowLightCameraCapability = 0;
    RenderWideGamutImagesAtDisplayTime = 1;
}
2024-03-15 21:35:33.079 dumper[1024:9851] Platform: {
    hardwareClass = Mac;
    hardwareIdentifier = "MacPro7,1";
    hardwareModel = "MacPro7,1";
    isInternalInstall = 0;
    mapsFeatureFreedomEnabled = 0;
    osAndBuildVersion = "14.4.23E214";
    osVersion = "14.4";
    productName = macOS;
    supportsAdvancedMap = 0;
    supportsForceTouch = 0;
    supportsNavigation = 0;
    supportsRealisticTiles = 0;
}

**Comment by notjosh** [comment]
Oh weird, `RenderWideGamutImagesAtDisplayTime` is the value I use as a substitute, which you still get as `1`, so something else must be up. Hold that thought!

Thanks for getting onto it so quick :)

**Comment by notjosh** [comment]
For reference later, here's how the output is on 14.3.1 (Intel)

```
2024-03-15 21:40:11.838 dumper[30239:78519] macOS version: Version 14.3.1 (Build 23D60)
2024-03-15 21:40:11.838 dumper[30239:78519] Architecture: x86_64
2024-03-15 21:40:11.838 dumper[30239:78519] GPUs (
        {
        MTLGPUFamilyApple1 = 0;
        MTLGPUFamilyApple2 = 0;
        MTLGPUFamilyApple3 = 0;
        MTLGPUFamilyApple4 = 0;
        MTLGPUFamilyApple5 = 0;
        MTLGPUFamilyApple6 = 0;
        MTLGPUFamilyApple7 = 0;
        MTLGPUFamilyApple8 = 0;
        MTLGPUFamilyApple9 = 0;
        MTLGPUFamilyCommon1 = 1;
        MTLGPUFamilyCommon2 = 1;
        MTLGPUFamilyCommon3 = 1;
        MTLGPUFamilyMac2 = 1;
        MTLGPUFamilyMetal3 = 1;
        name = "AMD Radeon HD GFX10 Family Unknown Prototype";
    }
)
2024-03-15 21:40:11.838 dumper[30239:78519] {
    DeviceSupportsActiveNFCReadingOnly = 0;
    DeviceSupportsAdvancedMapRendering = "<null>";
    DeviceSupportsCorrectedTemperature = 0;
    DeviceSupportsEnhancedMultitasking = 0;
    DeviceSupportsHeartRateVariability = 1;
    DeviceSupportsSideButtonClickSpeed = 0;
    DeviceSupportsSingleCameraPortrait = 0;
    DeviceSupportsStereoAudioRecording = 0;
    FrontCameraOffsetFromDisplayCenter = "<null>";
    FrontFacingCameraAutoHDRCapability = 0;
    RearFacingCameraMaxVideoZoomFactor = "<null>";
    RearFacingCameraModuleSerialNumber = "<null>";
    RearFacingLowLightCameraCapability = 0;
    RenderWideGamutImagesAtDisplayTime = 1;
}
2024-03-15 21:40:11.841 dumper[30239:78519] Platform: {
    hardwareClass = Mac;
    hardwareIdentifier = "iMac19,1";
    hardwareModel = "iMac19,1";
    isInternalInstall = 0;
    mapsFeatureFreedomEnabled = 0;
    osAndBuildVersion = "14.3.1.23D60";
    osVersion = "14.3.1";
    productName = macOS;
    supportsAdvancedMap = 1;
    supportsForceTouch = 0;
    supportsNavigation = 0;
    supportsRealisticTiles = 0;
}
```

`DeviceSupportsAdvancedMapRendering` being `nil` is weird, but the 3d globe still works. I'm guessing they've changed that to be more strict in 14.4.

**Comment by 5T33Z0** [comment]
```
2024-03-16 05:57:21.703 dumper[1113:81912] macOS version: Version 14.4 (Build 23E214)
2024-03-16 05:57:21.703 dumper[1113:81912] Architecture: x86_64
2024-03-16 05:57:21.704 dumper[1113:81912] GPUs (
        {
        MTLGPUFamilyApple1 = 0;
        MTLGPUFamilyApple2 = 0;
        MTLGPUFamilyApple3 = 0;
        MTLGPUFamilyApple4 = 0;
        MTLGPUFamilyApple5 = 0;
        MTLGPUFamilyApple6 = 0;
        MTLGPUFamilyApple7 = 0;
        MTLGPUFamilyApple8 = 0;
        MTLGPUFamilyApple9 = 0;
        MTLGPUFamilyCommon1 = 1;
        MTLGPUFamilyCommon2 = 1;
        MTLGPUFamilyCommon3 = 1;
        MTLGPUFamilyMac2 = 1;
        MTLGPUFamilyMetal3 = 1;
        name = "Intel(R) UHD Graphics 630";
    }
)
2024-03-16 05:57:21.704 dumper[1113:81912] {
    DeviceSupportsActiveNFCReadingOnly = 0;
    DeviceSupportsAdvancedMapRendering = "<null>";
    DeviceSupportsCorrectedTemperature = 0;
    DeviceSupportsEnhancedMultitasking = 0;
    DeviceSupportsHeartRateVariability = 1;
    DeviceSupportsSideButtonClickSpeed = 0;
    DeviceSupportsSingleCameraPortrait = 0;
    DeviceSupportsStereoAudioRecording = 0;
    FrontCameraOffsetFromDisplayCenter = "<null>";
    FrontFacingCameraAutoHDRCapability = 0;
    RearFacingCameraMaxVideoZoomFactor = "<null>";
    RearFacingCameraModuleSerialNumber = "<null>";
    RearFacingLowLightCameraCapability = 0;
    RenderWideGamutImagesAtDisplayTime = 1;
}
2024-03-16 05:57:21.710 dumper[1113:81912] Platform: {
    hardwareClass = Mac;
    hardwareIdentifier = "MacBookPro15,2";
    hardwareModel = "MacBookPro15,2";
    isInternalInstall = 0;
    mapsFeatureFreedomEnabled = 0;
    osAndBuildVersion = "14.4.23E214";
    osVersion = "14.4";
    productName = macOS;
    supportsAdvancedMap = 0;
    supportsForceTouch = 0;
    supportsNavigation = 0;
    supportsRealisticTiles = 0;
}
```

**Comment by 5T33Z0** [comment]
This id from my Lenovo T530 which uses Intel HD 4000 Graphics:

```
2024-03-16 13:25:25.536 dumper[889:9635] macOS version: Version 14.4 (Build 23E214)
2024-03-16 13:25:25.536 dumper[889:9635] Architecture: x86_64
2024-03-16 13:25:25.536 dumper[889:9635] GPUs (
        {
        MTLGPUFamilyApple1 = 0;
        MTLGPUFamilyApple2 = 0;
        MTLGPUFamilyApple3 = 0;
        MTLGPUFamilyApple4 = 0;
        MTLGPUFamilyApple5 = 0;
        MTLGPUFamilyApple6 = 0;
        MTLGPUFamilyApple7 = 0;
        MTLGPUFamilyApple8 = 0;
        MTLGPUFamilyApple9 = 0;
        MTLGPUFamilyCommon1 = 1;
        MTLGPUFamilyCommon2 = 1;
        MTLGPUFamilyCommon3 = 0;
        MTLGPUFamilyMac2 = 0;
        MTLGPUFamilyMetal3 = 0;
        name = "Intel HD Graphics 4000";
    }
)
2024-03-16 13:25:25.536 dumper[889:9635] {
    DeviceSupportsActiveNFCReadingOnly = 0;
    DeviceSupportsAdvancedMapRendering = "<null>";
    DeviceSupportsCorrectedTemperature = 0;
    DeviceSupportsEnhancedMultitasking = 0;
    DeviceSupportsHeartRateVariability = 1;
    DeviceSupportsSideButtonClickSpeed = 0;
    DeviceSupportsSingleCameraPortrait = 0;
    DeviceSupportsStereoAudioRecording = 0;
    FrontCameraOffsetFromDisplayCenter = "<null>";
    FrontFacingCameraAutoHDRCapability = 0;
    RearFacingCameraMaxVideoZoomFactor = "<null>";
    RearFacingCameraModuleSerialNumber = "<null>";
    RearFacingLowLightCameraCapability = 0;
    RenderWideGamutImagesAtDisplayTime = 1;
}
2024-03-16 13:25:25.541 dumper[889:9635] Platform: {
    hardwareClass = Mac;
    hardwareIdentifier = "MacBookPro10,1";
    hardwareModel = "MacBookPro10,1";
    isInternalInstall = 0;
    mapsFeatureFreedomEnabled = 0;
    osAndBuildVersion = "14.4.23E214";
    osVersion = "14.4";
    productName = macOS;
    supportsAdvancedMap = 0;
    supportsForceTouch = 0;
    supportsNavigation = 0;
    supportsRealisticTiles = 0;
}
```

**Comment by narcyzzo** [comment]
2024-03-17 00:19:16.905 dumper[3372:23465] macOS version: Version 14.4 (Build 23E214)
2024-03-17 00:19:16.905 dumper[3372:23465] Architecture: x86_64
2024-03-17 00:19:16.905 dumper[3372:23465] GPUs (
        {
        MTLGPUFamilyApple1 = 0;
        MTLGPUFamilyApple2 = 0;
        MTLGPUFamilyApple3 = 0;
        MTLGPUFamilyApple4 = 0;
        MTLGPUFamilyApple5 = 0;
        MTLGPUFamilyApple6 = 0;
        MTLGPUFamilyApple7 = 0;
        MTLGPUFamilyApple8 = 0;
        MTLGPUFamilyApple9 = 0;
        MTLGPUFamilyCommon1 = 1;
        MTLGPUFamilyCommon2 = 1;
        MTLGPUFamilyCommon3 = 1;
        MTLGPUFamilyMac2 = 1;
        MTLGPUFamilyMetal3 = 1;
        name = "Intel(R) UHD Graphics 630";
    }
)
2024-03-17 00:19:16.905 dumper[3372:23465] {
    DeviceSupportsActiveNFCReadingOnly = 0;
    DeviceSupportsAdvancedMapRendering = 0;
    DeviceSupportsCorrectedTemperature = 0;
    DeviceSupportsEnhancedMultitasking = 0;
    DeviceSupportsHeartRateVariability = 1;
    DeviceSupportsSideButtonClickSpeed = 0;
    DeviceSupportsSingleCameraPortrait = 0;
    DeviceSupportsStereoAudioRecording = 0;
    FrontCameraOffsetFromDisplayCenter = "<null>";
    FrontFacingCameraAutoHDRCapability = 0;
    RearFacingCameraMaxVideoZoomFactor = "<null>";
    RearFacingCameraModuleSerialNumber = "<null>";
    RearFacingLowLightCameraCapability = 0;
    RenderWideGamutImagesAtDisplayTime = 1;
}
2024-03-17 00:19:16.909 dumper[3372:23465] Platform: {
    hardwareClass = Mac;
    hardwareIdentifier = "MacBookPro16,4";
    hardwareModel = "MacBookPro16,4";
    isInternalInstall = 0;
    mapsFeatureFreedomEnabled = 0;
    osAndBuildVersion = "14.4.23E214";
    osVersion = "14.4";
    productName = macOS;
    supportsAdvancedMap = 0;
    supportsForceTouch = 0;
    supportsNavigation = 0;
    supportsRealisticTiles = 0;
}

**Comment by narcyzzo** [comment]
2024-06-18 15:45:51.194 dumper[3084:26292] macOS version: Version 15.0 (Build 24A5264n)
2024-06-18 15:45:51.194 dumper[3084:26292] Architecture: x86_64
2024-06-18 15:45:51.194 dumper[3084:26292] GPUs (
        {
        MTLGPUFamilyApple1 = 0;
        MTLGPUFamilyApple2 = 0;
        MTLGPUFamilyApple3 = 0;
        MTLGPUFamilyApple4 = 0;
        MTLGPUFamilyApple5 = 0;
        MTLGPUFamilyApple6 = 0;
        MTLGPUFamilyApple7 = 0;
        MTLGPUFamilyApple8 = 0;
        MTLGPUFamilyApple9 = 0;
        MTLGPUFamilyCommon1 = 1;
        MTLGPUFamilyCommon2 = 1;
        MTLGPUFamilyCommon3 = 1;
        MTLGPUFamilyMac2 = 1;
        MTLGPUFamilyMetal3 = 1;
        name = "AMD Radeon HD GFX10 Family Unknown Prototype";
    }
)
2024-06-18 15:45:51.194 dumper[3084:26292] {
    DeviceSupportsActiveNFCReadingOnly = 0;
    DeviceSupportsAdvancedMapRendering = "<null>";
    DeviceSupportsCorrectedTemperature = 0;
    DeviceSupportsEnhancedMultitasking = 0;
    DeviceSupportsHeartRateVariability = 1;
    DeviceSupportsSideButtonClickSpeed = 0;
    DeviceSupportsSingleCameraPortrait = 0;
    DeviceSupportsStereoAudioRecording = 0;
    FrontCameraOffsetFromDisplayCenter = "<null>";
    FrontFacingCameraAutoHDRCapability = 0;
    RearFacingCameraMaxVideoZoomFactor = "<null>";
    RearFacingCameraModuleSerialNumber = "<null>";
    RearFacingLowLightCameraCapability = 0;
    RenderWideGamutImagesAtDisplayTime = 1;
}
2024-06-18 15:45:51.197 dumper[3084:26292] Platform: {
    hardwareClass = Mac;
    hardwareIdentifier = "MacPro7,1";
    hardwareModel = "MacPro7,1";
    isInternalInstall = 0;
    mapsFeatureFreedomEnabled = 0;
    osAndBuildVersion = "15.0.24A5264n";
    osVersion = "15.0";
    productName = macOS;
    supportsAdvancedMap = 1;
    supportsForceTouch = 0;
    supportsNavigation = 0;
    supportsRealisticTiles = 0;
}

**Comment by narcyzzo** [comment]
@5T33Z0 can u confirm UHD 620 working for u?

**Comment by 5T33Z0** [comment]
@narcyzzo Yes, I checked it yesterday. That's why closed the issue.
